package utils;

import java.util.*;

public class StaticData {

    public static String createdProductName;
    public static String selectedContainer;
    public static String locationToSearch;
    public static String productNameToAssign;
    public static String productTypeToAssign;
    public static String productLocationToAssign;
    public static String productToAssign;
    public static String productNameToSearch;
    public static String productStatusToSearch;
    public static String duplicateProductCode;
    public static String duplicateProductType;
    public static String productTypeForContainer;
    public static String productLocationForContainer;
    public static String productTitleName;
    public static String productTypeStatus;
    public static String activeRecordName;
    public static String uniqueName;
    public static String productCode;
    public static String productName;
    public static String location;
    public static String toLocation;
    public static String assignFromDate;
    public static String assignTillDate;
    public static Random randNum = new Random();
    public static String productTypeName;
    public static List<String> barCodeValues = new ArrayList<>();
    public static String productTypesToAssign;
    public static List<String> productNamesToAssign = new ArrayList<>();
    public static List<String> productLocationsToAssign = new ArrayList<>();
    public static List<String> productsToAssign = new ArrayList<>();
    public static List<String> containerProductType = new ArrayList<>();
    public static String searchUniqueName;
    public static String searchStatus;
    public static String rowName;
    public static String userName;
    public static String productAcceptancePendingByUser;
    public static List<String> productNamesPendingByUser = new ArrayList<>();
    public static Map<String, String> productNamesWithCount = new HashMap<>();
    public static String productCountForPendingByUserWidget;
    public static String allReturnOverDueProductCount;
    public static String shiftReturnOverDueProductCount;
    public static List<String> productInMyProductList = new ArrayList<>();
    public static int productCountForLocationWidget;
    public static String inTransitProductCount;
    public static String prodType;
    public static List<String> productsAcceptancePendingByMangerCA = new ArrayList<>();
    public static List<String> productsAcceptancePendingByMangerPM = new ArrayList<>();
    public static List<String> productsAcceptancePendingByMangerNU = new ArrayList<>();
    public static List<String> pendingByManagerOtherLocation = new ArrayList<>();
    public static String productManagerLocation;
    public static String normalUserLocation;
    public static int userCount;
    public static String validBarcode;
    public static String locationName;
    public static String companyAdminLocationName;
    public static List<String> departmentNameList = new ArrayList<>();
    public static List<String> usersInTheDepartment = new ArrayList<>();
    public static List<String> allUserNameList = new ArrayList<>();
    public static String departmentNameToVerify;
    public static String barCodeNameToProductAssignSearch;
    public static List<String> parentLocationNameList = new ArrayList<>();
    public static List<String> childLocationNameList = new ArrayList<>();
    public static List<String> productTypeNamesForProductAssignment = new ArrayList<>();
    public static String productTypeToGetProductName;
    public static String productNameToGetProducts;
    public static List<String> productNamesForProductAssignment = new ArrayList<>();
    public static String totalProductCountBasedOnStatus;
    public static String totalProductCountBasedOnLocation;
    public static String currentTimeToTest;
}
