package Action;

import org.openqa.selenium.WebDriver;
import pageobjects.SelfAssignmentPage;

public class SelfAssignmentAction {
    WebDriver driver;
    SelfAssignmentPage selfAssignmentPage;
    ProductAssignmentAction productAssignment;


    public SelfAssignmentAction(WebDriver driver) {
        this.driver = driver;
        selfAssignmentPage = new SelfAssignmentPage(driver);
        productAssignment = new ProductAssignmentAction(driver);
    }

    public void navigateToMyProduct() {
        selfAssignmentPage.clickFullMenuDropDown();
        selfAssignmentPage.clickAssetManagement();
        selfAssignmentPage.clickMyProduct();
    }

    public void verifySelfAssignmentPage() {
        selfAssignmentPage.clickSelfAssignment();
        selfAssignmentPage.verifyProductAssignment();
    }

    public void verifyPrePopulatedUserName() {
        selfAssignmentPage.verifyAutoGeneratedUserName();
    }

    public void createTermsAndConditionProduct() {
        selfAssignmentPage.createTermsAndConditionProduct();
    }

    public void verifyTermsAndCondition() {
        selfAssignmentPage.clickTermsAndCondition();
        selfAssignmentPage.downloadTermAndConditionDocument();
        selfAssignmentPage.downloadAndVerifyTermsAndCondition();
        selfAssignmentPage.clickSaveButton();
    }

}
